# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0003_auto_20161213_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todolist',
        ),
    ]
