# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0004_delete_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbookuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddressBookUser',
        ),
    ]
