# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0005_auto_20161220_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodlightSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('luminance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('humidity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deviceStatus', models.BooleanField()),
                ('temperature', models.IntegerField()),
            ],
        ),
    ]
