# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0006_floodlightsensor_humiditysensor_temperaturesensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
