# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0007_auto_20170101_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodlightsensor',
            name='luminance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='humiditysensor',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
