# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0008_auto_20170102_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HumiditySensor',
            new_name='HumiditySensor1',
        ),
    ]
