# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0009_auto_20170104_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HumiditySensor1',
            new_name='HumiditySensor',
        ),
    ]
