# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOTEWMPApp', '0010_auto_20170104_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
